DROP TABLE IF EXISTS `printers`;
CREATE TABLE `printers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `brand` varchar(255) DEFAULT NULL,
  `model` varchar(255) DEFAULT NULL,
  `oem` varchar(20) DEFAULT NULL,
  `partnr` varchar(20) DEFAULT NULL,
  `technology` varchar(45) DEFAULT NULL,
  `technologie` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `categorie` varchar(255) DEFAULT NULL,
  `multifonction` tinyint(1) NOT NULL DEFAULT '0',
  `numerisation` tinyint(1) NOT NULL DEFAULT '0',
  `copie` tinyint(1) NOT NULL DEFAULT '0',
  `rectoverso` varchar(255) DEFAULT NULL,
  `rectoverso_mode` varchar(255) DEFAULT NULL,
  `rectoverso_auto` varchar(255) DEFAULT NULL,
  `couleur` tinyint(1) NOT NULL DEFAULT '0',
  `format` varchar(255) DEFAULT NULL,
  `connectivite` varchar(255) DEFAULT NULL,
  `ppm_noir` decimal(10,2) DEFAULT NULL,
  `ppm_couleur` decimal(10,2) DEFAULT NULL,
  `date_fabrication` date DEFAULT NULL,
  `color` varchar(20) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `star` tinyint(1) NOT NULL DEFAULT '0',
  `volume` float DEFAULT '0',
  `segmentation` varchar(20) DEFAULT NULL,
  `argument` text NOT NULL,
  `contrat` int(1) NOT NULL DEFAULT '0',
  `stock` tinyint(1) NOT NULL DEFAULT '0',
  `product_id` int(11) NOT NULL,
  `bechlem` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `product_id` (`product_id`),
  KEY `technology` (`technology`)
) ENGINE=InnoDB AUTO_INCREMENT=46712 DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS `printers_supplies`;
CREATE TABLE `printers_supplies` (
  `printer_id` int(11) DEFAULT NULL,
  `supply_id` int(11) DEFAULT NULL,
  `created` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS `products`;
CREATE TABLE `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `sku` varchar(45) DEFAULT NULL,
  `ean` varchar(45) DEFAULT NULL,
  `upc` varchar(45) DEFAULT NULL,
  `partnr` varchar(255) DEFAULT NULL,
  `name` varchar(500) DEFAULT NULL,
  `brand` varchar(45) DEFAULT NULL,
  `price` decimal(10,2) DEFAULT NULL,
  `bechlem_id` varchar(255) DEFAULT NULL,
  `model` varchar(20) DEFAULT NULL,
  `model_id` int(11) DEFAULT NULL,
  `star` tinyint(1) NOT NULL DEFAULT '0',
  `designation` varchar(255) DEFAULT NULL,
  `icecat` int(11) DEFAULT NULL,
  `icecat_pdf` varchar(255) DEFAULT NULL,
  `code_aster` varchar(200) DEFAULT NULL,
  `url_fiche` varchar(255) DEFAULT NULL,
  `meta_description` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `model_id` (`model_id`),
  KEY `model` (`model`),
  KEY `brand` (`brand`),
  KEY `bechlem_id` (`bechlem_id`)
) ENGINE=InnoDB AUTO_INCREMENT=105089 DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS `supplies`;
CREATE TABLE `supplies` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `oem` varchar(45) DEFAULT NULL,
  `partnr` varchar(20) DEFAULT NULL,
  `technology` varchar(45) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `color` varchar(200) DEFAULT NULL,
  `color_uk` varchar(255) DEFAULT NULL,
  `color_es` varchar(255) DEFAULT NULL,
  `color_it` varchar(255) DEFAULT NULL,
  `color_de` varchar(255) DEFAULT NULL,
  `model` varchar(255) DEFAULT NULL,
  `duree_extension` int(11) DEFAULT NULL,
  `capacity_page` int(11) DEFAULT NULL,
  `capacity_ml` decimal(10,0) DEFAULT NULL,
  `capacity_gr` int(11) DEFAULT NULL,
  `product_id` int(11) NOT NULL,
  `bechlem` varchar(255) DEFAULT NULL,
  `mpn` varchar(255) DEFAULT NULL,
  `mpn_m` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `product_id` (`product_id`),
  KEY `bechlem` (`bechlem`)
) ENGINE=InnoDB AUTO_INCREMENT=58117 DEFAULT CHARSET=utf8;
